name: email_address
description: Provides a e-mail address value type.
version: 1.0.0
repository: https://github.com/LitGroup/email-address.dart

environment:
  sdk: ^3.1.3

dependencies:
  email_validator: ^2.1.17
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
